# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- goos:
  - linux
  - windows
  - darwin
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: amd64
  ldflags:
    - -s -w -X FLEcli/cmd.version={{.Version}} -X FLEcli/cmd.commit={{.Commit}} -X FLEcli/cmd.date={{.Date}} -X=FLEcli/cmd.builtBy=goReleaser
  env:
  - CGO_ENABLED=0

dockers:
- goos: linux
  goarch: amd64
  goarm: ''
  binaries:
  - FLEcli
  image_templates:
  - "on4kjm/flecli:latest"
  - "on4kjm/flecli:{{ .Tag }}"
  # Skips the docker push. Could be useful if you also do draft releases.
  # If set to auto, the release will not be pushed to the docker repository
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  # Defaults to false.
  skip_push: false
  # Path to the Dockerfile (from the project root).
  dockerfile: docker/Dockerfile

  # Template of the docker build flags.
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"

archives:
- replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Linux
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
  files:
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
