#Continuous integration action
name: Go Build & Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.3'
    - run: go mod download
    - name: Build & Test
      run: |
        go build -v .
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --snapshot  --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v1
      with:
        name: FLEcli_darwin_amd64
        path: /home/runner/work/FLEcli/FLEcli/dist/FLEcli_darwin_amd64/FLEcli