#Continuous integration action
# largely inspired by https://brunopaz.dev/blog/building-a-basic-ci-cd-pipeline-for-a-golang-application-using-github-actions
name: Build & Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          # export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          go get -u golang.org/x/lint/golint 
          golint -set_exit_status ./...


  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.3'
    - run: go mod download
    - name: Build & Test
      run: |
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --snapshot --skip-publish --rm-dist