#Continuous integration action
name: Go Build & Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.3'
    - run: go mod download
    - name: Build & Test
      run: |
        go build -v .
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --snapshot --skip-publish --rm-dist